// auto-updater.cjs — Binary auto-update for Zeus desktop via electron-updater.
//
// Uses electron-updater to check GitHub releases for new versions of the
// desktop app. When an update is found, it downloads the new installer in
// the background and prompts the user to restart and install.
//
// The GitHub release must include:
//   - The NSIS installer (Zeus-<version>-win-x64.exe)
//   - The latest.yml file (generated by electron-builder when publish config is set)
//
// electron-updater reads latest.yml to determine the latest version and
// download URL. It verifies the file hash before installing.
//
// Exports:
//   initAutoUpdater(mainWindowRef) — initialize and start checking
//   checkForUpdatesNow() — manual check (e.g. from "Check for Updates" button)
//   downloadUpdate() — start downloading after user accepts
//   installUpdateAndRestart() — quit and install the downloaded update
//   getUpdateStatus() — current status object
//   onUpdateEvent(callback) — subscribe to status changes

"use strict";

const { app, dialog, Notification } = require("electron");

let autoUpdater = null;
let mainWindowRef = null;
let updateAvailable = null;
let updateDownloaded = null;
let isChecking = false;
let isDownloading = false;
let downloadProgress = null;
let lastError = null;
let initTime = 0;
let periodicCheckTimer = null;
const eventListeners = new Set();

// Check every 4 hours
const PERIODIC_CHECK_INTERVAL_MS = 4 * 60 * 60 * 1000;
// Wait 10 seconds after app launch before first check
const INITIAL_CHECK_DELAY_MS = 10 * 1000;

// ---------------------------------------------------------------------------
// Status helpers
// ---------------------------------------------------------------------------

function getUpdateStatus() {
  return {
    initialized: autoUpdater !== null,
    checking: isChecking,
    downloading: isDownloading,
    updateAvailable: updateAvailable,
    updateDownloaded: updateDownloaded,
    downloadProgress: downloadProgress,
    error: lastError,
    currentVersion: app.getVersion(),
    checkedAt: initTime || null,
  };
}

function emitEvent(type, data) {
  const event = { type, data, timestamp: Date.now() };
  for (const cb of eventListeners) {
    try {
      cb(event);
    } catch (e) {
      console.error("[auto-updater] event listener error:", e.message);
    }
  }
  // Also send to renderer if window is available
  if (mainWindowRef) {
    const win = mainWindowRef.get?.();
    if (win && !win.isDestroyed() && win.webContents) {
      win.webContents.send("zeus:auto-updater:event", event);
    }
  }
}

function onUpdateEvent(callback) {
  eventListeners.add(callback);
  return () => eventListeners.delete(callback);
}

// ---------------------------------------------------------------------------
// Initialization
// ---------------------------------------------------------------------------

function initAutoUpdater(mainWindowRefArg) {
  mainWindowRef = mainWindowRefArg;

  try {
    autoUpdater = require("electron-updater").autoUpdater;
  } catch (e) {
    console.error("[auto-updater] electron-updater not available:", e.message);
    lastError = "electron-updater package not installed";
    return false;
  }

  // Configuration
  autoUpdater.autoDownload = false;  // Don't auto-download — ask the user first
  autoUpdater.autoInstallOnAppQuit = true;  // Install on quit if downloaded
  autoUpdater.allowDowngrade = false;

  // --- Event handlers ---

  autoUpdater.on("checking-for-update", () => {
    isChecking = true;
    lastError = null;
    emitEvent("checking-for-update", {});
  });

  autoUpdater.on("update-available", (info) => {
    isChecking = false;
    updateAvailable = {
      version: info.version,
      releaseDate: info.releaseDate,
      releaseNotes: info.releaseNotes,
    };
    emitEvent("update-available", updateAvailable);

    // Show a notification prompting the user to download
    showUpdateAvailableNotification(updateAvailable);
  });

  autoUpdater.on("update-not-available", (info) => {
    isChecking = false;
    updateAvailable = null;
    emitEvent("update-not-available", { version: info?.version });
  });

  autoUpdater.on("error", (err) => {
    isChecking = false;
    isDownloading = false;
    lastError = err?.message || String(err);
    emitEvent("error", { message: lastError });
    console.error("[auto-updater] error:", lastError);
  });

  autoUpdater.on("download-progress", (progress) => {
    downloadProgress = {
      percent: Math.round(progress.percent || 0),
      transferred: progress.transferred,
      total: progress.total,
      bytesPerSecond: progress.bytesPerSecond,
    };
    emitEvent("download-progress", downloadProgress);
  });

  autoUpdater.on("update-downloaded", (info) => {
    isDownloading = false;
    updateDownloaded = {
      version: info.version,
      releaseDate: info.releaseDate,
    };
    emitEvent("update-downloaded", updateDownloaded);

    // Show notification prompting the user to restart
    showUpdateDownloadedNotification(updateDownloaded);
  });

  // Schedule first check after a delay
  initTime = Date.now();
  startPeriodicChecks();

  return true;
}

function startPeriodicChecks() {
  if (!autoUpdater) return;
  // First check after a delay
  setTimeout(() => {
    checkForUpdatesNow().catch(() => {});
  }, INITIAL_CHECK_DELAY_MS);
  // Periodic checks
  if (periodicCheckTimer) {
    clearInterval(periodicCheckTimer);
  }
  periodicCheckTimer = setInterval(() => {
    checkForUpdatesNow().catch(() => {});
  }, PERIODIC_CHECK_INTERVAL_MS);
}

function stopPeriodicChecks() {
  if (periodicCheckTimer) {
    clearInterval(periodicCheckTimer);
    periodicCheckTimer = null;
  }
}

// ---------------------------------------------------------------------------
// Public actions
// ---------------------------------------------------------------------------

async function checkForUpdatesNow() {
  if (!autoUpdater) {
    return { ok: false, error: "auto-updater not initialized" };
  }
  if (isChecking) {
    return { ok: false, error: "already checking" };
  }
  // Set the flag immediately (before the async call) to close the race window
  isChecking = true;
  try {
    await autoUpdater.checkForUpdates();
    // isChecking is reset by the "update-available" / "update-not-available" / "error" handlers
    return { ok: true, status: getUpdateStatus() };
  } catch (e) {
    isChecking = false;
    lastError = e?.message || String(e);
    return { ok: false, error: lastError };
  }
}

async function downloadUpdate() {
  if (!autoUpdater) {
    return { ok: false, error: "auto-updater not initialized" };
  }
  if (!updateAvailable) {
    return { ok: false, error: "no update available" };
  }
  if (isDownloading) {
    return { ok: false, error: "already downloading" };
  }
  isDownloading = true;
  try {
    await autoUpdater.downloadUpdate();
    // isDownloading is reset by the "update-downloaded" / "error" event handlers
    return { ok: true };
  } catch (e) {
    lastError = e?.message || String(e);
    return { ok: false, error: lastError };
  } finally {
    // Safety net: if neither "update-downloaded" nor "error" fired,
    // ensure the flag doesn't get stuck.
    // (The event handlers will have already set it to false in the normal path.)
    if (updateDownloaded) {
      isDownloading = false;
    }
  }
}

function installUpdateAndRestart() {
  if (!autoUpdater || !updateDownloaded) {
    return false;
  }
  // setImmediate ensures the renderer gets the event before we quit
  setImmediate(() => {
    autoUpdater.quitAndInstall(false, true);  // isSilent=false, isForceRunAfter=true
  });
  return true;
}

// ---------------------------------------------------------------------------
// Notifications
// ---------------------------------------------------------------------------

function showUpdateAvailableNotification(info) {
  const title = "Zeus Update Available";
  const body = `Version ${info.version} is available. Click to download.`;

  if (Notification.isSupported()) {
    const notif = new Notification({ title, body, silent: false });
    notif.on("click", () => {
      // Trigger download via the renderer's update flow
      const win = mainWindowRef?.get?.();
      if (win && !win.isDestroyed()) {
        win.webContents.send("zeus:auto-updater:notification-clicked", {
          action: "download",
          version: info.version,
        });
        if (!win.isVisible()) win.show();
        win.focus();
      }
    });
    notif.show();
  }
}

function showUpdateDownloadedNotification(info) {
  const title = "Zeus Update Ready";
  const body = `Version ${info.version} is downloaded. Click to restart and install.`;

  if (Notification.isSupported()) {
    const notif = new Notification({ title, body, silent: false });
    notif.on("click", () => {
      installUpdateAndRestart();
    });
    notif.show();
  }
}

// ---------------------------------------------------------------------------
// Cleanup
// ---------------------------------------------------------------------------

function destroyAutoUpdater() {
  if (periodicCheckTimer) {
    clearInterval(periodicCheckTimer);
    periodicCheckTimer = null;
  }
  eventListeners.clear();
}

module.exports = {
  initAutoUpdater,
  checkForUpdatesNow,
  downloadUpdate,
  installUpdateAndRestart,
  getUpdateStatus,
  onUpdateEvent,
  destroyAutoUpdater,
  startPeriodicChecks,
  stopPeriodicChecks,
};
